const mongoose = require("mongoose")

// Contract schema to store full contract details with explicitly defined fields
// matching the frontend contract form structure
const ContractSchema = new mongoose.Schema(
  {
    contractNumber: { type: String, required: true, unique: true },
    department: { type: String, default: "Sales" },
    status: { type: String, default: "Draft" },
    rejectionReason: { type: String, default: "" },
    
    page1: {
      celebratorName: { type: String, default: "" },
      celebratorAddress: { type: String, default: "" },
      celebratorLandline: { type: String, default: "" },
      celebratorMobile: { type: String, default: "" },
      celebratorEmail: { type: String, default: "" },
      representativeName: { type: String, default: "" },
      representativeRelationship: { type: String, default: "" },
      representativeAddress: { type: String, default: "" },
      representativeEmail: { type: String, default: "" },
      representativeMobile: { type: String, default: "" },
      representativeLandline: { type: String, default: "" },
      coordinatorName: { type: String, default: "" },
      coordinatorMobile: { type: String, default: "" },
      coordinatorLandline: { type: String, default: "" },
      coordinatorAddress: { type: String, default: "" },
      coordinatorEmail: { type: String, default: "" },
      officeLocation: { type: String, default: "" },
      eventDate: { type: String, default: "" },
      occasion: { type: String, default: "" },
      serviceStyle: { type: String, default: "" },
      venue: { type: String, default: "" },
      hall: { type: String, default: "" },
      ingressTime: { type: String, default: "" },
      cocktailTime: { type: String, default: "" },
      address: { type: String, default: "" },
      arrivalOfGuests: { type: String, default: "" },
      servingTime: { type: String, default: "" },
      totalGuests: { type: String, default: "" },
      totalVIP: { type: String, default: "" },
      totalRegular: { type: String, default: "" },
      themeSetup: { type: String, default: "" },
      colorMotif: { type: String, default: "" },
      vipTableType: { type: String, default: "" },
      regularTableType: { type: String, default: "" },
      vipTableSeats: { type: String, default: "" },
      regularTableSeats: { type: String, default: "" },
      vipTableQuantity: { type: String, default: "" },
      regularTableQuantity: { type: String, default: "" },
      vipUnderliner: { type: String, default: "" },
      vipTopper: { type: String, default: "" },
      vipNapkin: { type: String, default: "" },
      guestUnderliner: { type: String, default: "" },
      guestTopper: { type: String, default: "" },
      guestNapkin: { type: String, default: "" },
      setupRemarks: { type: String, default: "" }
    },

    page2: {
      chairsMonoblock: { type: String, default: "" },
      chairsTiffany: { type: String, default: "" },
      chairsCrystal: { type: String, default: "" },
      chairsRustic: { type: String, default: "" },
      chairsKiddie: { type: String, default: "" },
      premiumChairs: { type: String, default: "" },
      totalChairs: { type: String, default: "" },
      chairsRemarks: { type: String, default: "" },
      flowerBackdrop: { type: String, default: "" },
      flowerGuestCenterpiece: { type: String, default: "" },
      flowerVipCenterpiece: { type: String, default: "" },
      flowerCakeTable: { type: String, default: "" },
      flowerRemarks: { type: String, default: "" },
      cakeNameCode: { type: String, default: "" },
      cakeFlavor: { type: String, default: "" },
      cakeSupplier: { type: String, default: "" },
      cakeSpecifications: { type: String, default: "" },
      celebratorsCar: { type: String, default: "" },
      emcee: { type: String, default: "" },
      soundSystem: { type: String, default: "" },
      tent: { type: String, default: "" },
      celebratorsChair: { type: String, default: "" },
      knowUsWebsite: { type: Boolean, default: false },
      knowUsFacebook: { type: Boolean, default: false },
      knowUsInstagram: { type: Boolean, default: false },
      knowUsFlyers: { type: Boolean, default: false },
      knowUsBillboard: { type: Boolean, default: false },
      knowUsWordOfMouth: { type: Boolean, default: false },
      knowUsVenueReferral: { type: Boolean, default: false },
      knowUsRepeatClient: { type: Boolean, default: false },
      knowUsBridalFair: { type: Boolean, default: false },
      knowUsFoodTasting: { type: Boolean, default: false },
      knowUsCelebrityReferral: { type: Boolean, default: false },
      knowUsOthers: { type: Boolean, default: false }
    },

    pageBuffet: {
      selectedPackage: { type: String, default: "" },
      cocktailSelections: { type: [String], default: [] },
      upgradeSelections125: { type: [String], default: [] },
      upgradeSelections150: { type: [String], default: [] },
      foodStations: { type: [Object], default: [] },
      appetizerUpgradeSelections125: { type: [String], default: [] },
      appetizerUpgradeSelections150: { type: [String], default: [] },
      soupSelections: { type: [String], default: [] },
      upgradeSoupSelections100: { type: [String], default: [] },
      breadSelections: { type: [String], default: [] },
      saladUpgradeSelections125: { type: [String], default: [] },
      saladUpgradeSelections150: { type: [String], default: [] },
      mainBeefSelections: { type: [String], default: [] },
      mainPorkSelections: { type: [String], default: [] },
      mainFishSelections: { type: [String], default: [] },
      mainSeafoodSelections: { type: [String], default: [] },
      mainChickenSelections: { type: [String], default: [] },
      mainPastaSelections: { type: [String], default: [] },
      mainNoodlesSelections: { type: [String], default: [] },
      mainVegSelections: { type: [String], default: [] },
      mainSideDishSelections: { type: [String], default: [] },
      riceSelections: { type: [String], default: [] },
      dessertSelections: { type: [String], default: [] },
      drinksSelections: { type: [String], default: [] }
    },
    page3: {
      pricePerPlate: { type: String, defaulyt: "" },
      cocktailHour: { type: String, default: "" },
      foodStations: { type: String, default: "" },
      appetizer: { type: String, default: "" },
      soup: { type: String, default: "" },
      bread: { type: String, default: "" },
      salad: { type: String, default: "" },
      mainEntree: { type: String, default: "" },
      rice: { type: String, default: "" },
      dessert: { type: String, default: "" },
      drinks: { type: String, default: "" },
      cakeName: { type: String, default: "" },
      roastedPig: { type: String, default: "" },
      roastedCalf: { type: String, default: "" },
      totalMenuCost: { type: String, default: "" },
      totalSpecialReqCost: { type: String, default: "" },
      mobilizationCharge: { type: String, default: "" },
      taxes: { type: String, default: "" },
      grandTotal: { type: String, default: "" },
      fortyPercentDueOn: { type: String, default: "" },
      fortyPercentAmount: { type: String, default: "" },
      fortyPercentReceivedBy: { type: String, default: "" },
      fortyPercentDateReceived: { type: String, default: "" },
      fullPaymentDueOn: { type: String, default: "" },
      fullPaymentAmount: { type: String, default: "" },
      fullPaymentReceivedBy: { type: String, default: "" },
      fullPaymentDateReceived: { type: String, default: "" },
      remarks: { type: String, default: "" }
    }
  },
  { timestamps: true }
)

module.exports = mongoose.model("Contract", ContractSchema)


